server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password : 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

