  
spring:
  datasource:
    url: jdbc:mariadb://semiclonedb.cyvml3ymtwdk.ap-northeast-2.rds.amazonaws.com:3306/semiclone?characterEncoding=UTF-8&useUnicode=yes
    driver-class-name: org.mariadb.jdbc.Driver
    username: semiclone
    password : vhplforqh4

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  messages:
    basename: validation


server:
  port: 8005
